detail::*_category::name(): Add missing noexcept
Fixes compilation
error: looser throw specifier for ...

Signed-off-by: Bernhard Reutner-Fischer <rep.dot.nop@gmail.com>